name: Aide CI Linux

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-16.04]
    
    steps:
    - uses: actions/checkout@v1
    - name: Install deps
      run: sudo apt install bison flex libgpg-error-dev libmhash-dev libpq-dev libcap-dev libaudit-dev libselinux1-dev libattr1-dev e2fslibs-dev libacl1-dev
    - name: autoconf
      run: sh autogen.sh
    - name: configure
      run: ./configure --with-selinux --with-posix-acl --with-capabilities --with-e2fsattrs
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
